import { type Cluster, type Motif, type Node, type Wrapped } from "../api";
import { motifLabels, motifOptions } from "../data/ui";
import { ClientTable } from "../components/ClientList";
import { GidButton, MetricCard, MoneyValue, Pager, Panel, Status } from "../components/UI";

export interface MotifsPageProps { list?: Wrapped<Motif>; loading: boolean; error: boolean; gid: string; onGid: (gid: string) => void; type: string; onType: (type: string) => void; offset: number; onPage: (offset: number) => void; onMotif: (id: string) => void }
export function MotifsPage({ list, loading, error, gid, onGid, type, onType, offset, onPage, onMotif }: Readonly<MotifsPageProps>) {
  return <><Panel title="Фильтры мотивов"><div className="mg-filters"><select aria-label="Тип мотива" value={type} onChange={event => onType(event.target.value)}><option value="">Все типы</option>{motifOptions.slice(1).map(value => <option value={value} key={value}>{motifLabels[value]}</option>)}</select><input aria-label="gid участника" inputMode="numeric" placeholder="gid участника" value={gid} onChange={event => onGid(event.target.value)}/><button onClick={() => { onType(""); onGid(""); }}>Сбросить</button></div></Panel><Panel title="Мотивы">{loading ? <Status message="Загружаем мотивы…"/> : error ? <Status tone="error" message="Не удалось загрузить мотивы."/> : list?.items.length ? <><div className="mg-table-scroll"><table><thead><tr><th>motif_id</th><th>Тип</th><th>Участники</th><th>Временной статус</th><th className="mg-num">Совместимый объём</th><th>Действие</th></tr></thead><tbody>{list.items.map(item => <tr key={item.motif_id}><td className="mg-mono">{item.motif_id}</td><td>{motifLabels[item.type] ?? item.type}</td><td className="mg-mono">{item.node_ids.join(" → ")}</td><td>{item.temporal_status === "compatible" ? "Совместим по датам" : "Структурный"}</td><td className="mg-num"><MoneyValue value={item.metrics.compatible_kzt}/></td><td><button className="mg-link" onClick={() => onMotif(item.motif_id)}>Детали</button></td></tr>)}</tbody></table></div><Pager offset={offset} pageSize={30} total={list.total ?? 0} onPage={onPage}/></> : <Status message="Мотивы не найдены. Если поиск усечён, отсутствие результата не означает отсутствия мотива."/>}</Panel><Status tone="warning" message="Поиск мотивов может быть усечён. Временная совместимость не доказывает происхождение конкретной суммы."/></>;
}

export interface MotifPageProps { motif?: Motif; loading: boolean; error: boolean; onClient: (gid: string) => void; onGraph: (gid: string) => void }
export function MotifPage({ motif, loading, error, onClient, onGraph }: Readonly<MotifPageProps>) {
  if (error) return <Status tone="error" message="Мотив не найден или API недоступен."/>;
  if (loading || !motif) return <Status message="Загружаем детали мотива…"/>;
  return <><Panel title={`${motif.motif_id} · ${motifLabels[motif.type] ?? motif.type}`}><div className="mg-chip-row"><span className="mg-chip">{motif.temporal_status === "compatible" ? "Совместим по датам" : "Структурный"}</span><span className="mg-chip">{motif.edges.length} связей</span><span className="mg-chip">Совместимый объём: <MoneyValue value={motif.metrics.compatible_kzt}/></span></div><p className="mg-help">Структурная и временная гипотеза для проверки аналитиком.</p></Panel><Panel title="Направленная схема"><div className="mg-flow">{motif.node_ids.map((gid, index) => <span key={gid + index}><GidButton gid={gid} onClick={onClient}/>{index < motif.node_ids.length - 1 && <b>→</b>}</span>)}</div><div className="mg-action-row"><button onClick={() => onGraph(motif.node_ids[0])}>Открыть окружение</button></div></Panel><Panel title="Подтверждающие рёбра"><div className="mg-table-scroll"><table><thead><tr><th>Источник</th><th>Получатель</th><th className="mg-num">Сумма</th><th>Операций</th></tr></thead><tbody>{motif.edges.map((edge, index) => <tr key={index}><td><GidButton gid={edge.source} onClick={onClient}/></td><td><GidButton gid={edge.target} onClick={onClient}/></td><td className="mg-num"><MoneyValue value={edge.sum_kzt}/></td><td>{edge.n_tx}</td></tr>)}</tbody></table></div></Panel><div className="mg-two-cols"><Panel title="Даты и операции"><p>Даты: {motif.metrics.dates.join(", ") || "Нет данных"}</p><p>Внутренние ID: <span className="mg-mono">{motif.supporting_transaction_ids.join(", ") || "Нет данных"}</span></p>{motif.metrics.confirmations.map((confirmation, index) => <p key={index}>Сопоставление {index + 1}: {confirmation.start_date} → {confirmation.end_date}; <MoneyValue value={confirmation.compatible_tiyn / 100}/>; ID {confirmation.transaction_ids.join(", ")}</p>)}</Panel><Panel title="Ограничения"><ul className="mg-limitations">{motif.limitations.map(item => <li key={item}>{item}</li>)}</ul><p className="mg-help">Однодневный порядок неизвестен. Совместимость не доказывает происхождение денег.</p></Panel></div></>;
}

export interface CommunitiesPageProps { clusters?: Cluster[]; loading: boolean; onCommunity: (id: number) => void }
export function CommunitiesPage({ clusters, loading, onCommunity }: Readonly<CommunitiesPageProps>) {
  return <><Panel title="Сообщества наблюдаемого графа">{loading ? <Status message="Загружаем сообщества…"/> : <div className="mg-table-scroll"><table><thead><tr><th>cluster_id</th><th>Клиенты</th><th>seed</th><th className="mg-num">Внутренний оборот</th><th>Лидеры gid</th><th>Структурная гипотеза</th><th>Действие</th></tr></thead><tbody>{clusters?.map(item => <tr key={item.cluster_id}><td>{item.cluster_id}</td><td>{item.n_nodes}</td><td>{item.n_seed}</td><td className="mg-num"><MoneyValue value={item.sum_kzt_internal}/></td><td className="mg-mono">{item.top_gids.slice(0, 2).join(", ")}</td><td>{item.hypothesis}</td><td><button className="mg-link" onClick={() => onCommunity(item.cluster_id)}>Открыть</button></td></tr>)}</tbody></table></div>}</Panel><Status tone="warning" message="Сообщества рассчитаны на ненаправленной проекции; денежные связи в графе остаются направленными."/></>;
}

export interface CommunityPageProps { cluster?: Cluster; loading: boolean; error: boolean; nodes?: Wrapped<Node>; nodesLoading: boolean; nodesError: boolean; offset: number; onPage: (offset: number) => void; onClient: (gid: string) => void; onGraph: (gid: string) => void }
export function CommunityPage({ cluster, loading, error, nodes, nodesLoading, nodesError, offset, onPage, onClient, onGraph }: Readonly<CommunityPageProps>) {
  if (error) return <Status tone="error" message="Сообщество не найдено."/>;
  if (loading || !cluster) return <Status message="Загружаем сообщество…"/>;
  return <><div className="mg-metric-grid"><MetricCard label="Клиентов" value={cluster.n_nodes} note={`Сообщество ${cluster.cluster_id}`}/><MetricCard label="seed" value={cluster.n_seed} note="В этом сообществе"/><MetricCard label="Внутренний оборот" value={<MoneyValue value={cluster.sum_kzt_internal}/>} note="Наблюдаемые переводы"/></div><Panel title="Структурная гипотеза"><p>{cluster.hypothesis}</p><p className="mg-help">Гипотеза описывает структуру, а не характеристики участников.</p></Panel><Panel title="Лидеры сообщества"><div className="mg-action-row">{cluster.top_gids.map(gid => <GidButton gid={gid} key={gid} onClick={onClient}/>)}</div></Panel><Panel title="Участники"><ClientTable items={nodes?.items} total={nodes?.total ?? 0} offset={offset} loading={nodesLoading} error={nodesError} onSelect={onClient} onGraph={onGraph} onPage={onPage}/></Panel></>;
}
