import type { MutableRefObject } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { metric, money, score, type Edge, type Neighborhood, type Node, type Summary, type Transaction, type Wrapped } from "../api";
import { Graph, type GraphViewport } from "../Graph";
import { ClientFilters, ClientTable, type ClientFiltersProps } from "../components/ClientList";
import { ClientHeader, GidButton, MetricCard, MoneyValue, Pager, Panel, PriorityBreakdown, RoleBadge, RuleTable, Status } from "../components/UI";

export interface GraphPageProps {
  filterProps: ClientFiltersProps; list?: Wrapped<Node>; listLoading: boolean; offset: number; onPage: (offset: number) => void;
  node?: Node; selected?: string; network?: Neighborhood; networkError: boolean; hops: number; onHops: (hops: number) => void;
  colorBy: "role" | "cluster"; onColorBy: (color: "role" | "cluster") => void; theme: "dark" | "light";
  tab: "list" | "graph" | "card"; onTab: (tab: "list" | "graph" | "card") => void;
  chosenEdge: Edge | null; onEdge: (edge: Edge | null) => void;
  viewportRef: MutableRefObject<GraphViewport | null>; centeredRef: MutableRefObject<string | undefined>;
  onSelect: (gid: string) => void; onClient: (gid: string) => void; onTransactions: (gid: string) => void;
}
export function GraphPage({ filterProps, list, listLoading, offset, onPage, node, selected, network, networkError, hops, onHops, colorBy, onColorBy, theme, tab, onTab, chosenEdge, onEdge, viewportRef, centeredRef, onSelect, onClient, onTransactions }: Readonly<GraphPageProps>) {
  return <><div className="mg-mobile-tabs"><button className={tab === "list" ? "active" : ""} onClick={() => onTab("list")}>Список</button><button className={tab === "graph" ? "active" : ""} onClick={() => onTab("graph")}>Граф</button><button className={tab === "card" ? "active" : ""} onClick={() => onTab("card")}>Карточка</button></div>{network?.truncated && <Status tone="warning" message={`Показано ${network.shown_nodes}/${network.available_nodes} узлов и ${network.shown_edges}/${network.available_edges} связей. Визуализация усечена.`}/>}<div className="mg-graph-workspace">
    <div className={`mg-graph-list ${tab === "list" ? "mobile-active" : ""}`}><Panel title="Клиенты"><details className="mg-graph-filters"><summary>Поиск и фильтры</summary><ClientFilters {...filterProps}/><p className="mg-help">Фильтры меняют список, а не окружение и оценки клиента.</p></details><p className="mg-muted">{listLoading ? "Загрузка…" : `${list?.total ?? 0} клиентов`}</p><div className="mg-client-list">{list?.items.map(item => <button key={item.gid} className={item.gid === selected ? "selected" : ""} onClick={() => { onSelect(item.gid); onTab("graph"); }}><span className="mg-gid">{item.gid}</span><RoleBadge role={item.role}/><b>{score(item.priority_score)}</b></button>)}</div><Pager offset={offset} pageSize={50} total={list?.total ?? 0} onPage={onPage}/></Panel></div>
    <section className={`mg-graph-center ${tab === "graph" ? "mobile-active" : ""}`}><div className="mg-graph-toolbar"><div><b>Окружение <span className="mg-gid">{selected ?? "—"}</span></b><small>1–2 перехода · направленные переводы</small></div><div><select aria-label="Число переходов" value={hops} onChange={event => onHops(Number(event.target.value))}><option value={1}>1 переход</option><option value={2}>2 перехода</option></select><select aria-label="Цвет графа" value={colorBy} onChange={event => onColorBy(event.target.value as "role" | "cluster")}><option value="role">По роли</option><option value="cluster">По сообществу</option></select></div></div><div className="mg-graph-canvas">{networkError ? <Status tone="error" message="Не удалось загрузить окружение."/> : network ? <Graph nodes={network.nodes} edges={network.edges} selected={selected} onSelect={gid => { onSelect(gid); onEdge(null); }} onEdge={onEdge} colorBy={colorBy} theme={theme} viewportRef={viewportRef} centeredRef={centeredRef}/> : <Status message="Загружаем направленное окружение…"/>}</div><div className="mg-graph-legend"><span><i className="mg-seed-symbol"/> seed</span><span><i className="mg-role-symbol"/> роль</span><span><i className="mg-boundary-symbol"/> граница depth=4</span><span>Стрелка — направление перевода</span></div>{chosenEdge && <div className="mg-edge-detail"><button aria-label="Закрыть сведения о связи" onClick={() => onEdge(null)}>×</button><strong className="mg-gid">{chosenEdge.source} → {chosenEdge.target}</strong><span><MoneyValue value={chosenEdge.sum_kzt}/> · {chosenEdge.n_tx} операций</span><button onClick={() => onClient(chosenEdge.target)}>Карточка получателя</button></div>}</section>
    <div className={`mg-graph-inspector ${tab === "card" ? "mobile-active" : ""}`}><Panel title="Выбранный клиент">{node ? <><strong className="mg-gid">{node.gid}</strong><div className="mg-chip-row"><RoleBadge role={node.role}/><span className="mg-chip">role_score {score(node.role_score)}</span><span className="mg-chip">priority {score(node.priority_score)}</span></div><p className="mg-evidence">{node.evidence}</p><div className="mg-keyvalues"><div><span>Вход</span><b><MoneyValue value={node.in_kzt}/></b></div><div><span>Выход</span><b><MoneyValue value={node.out_kzt}/></b></div><div><span>Сообщество / depth</span><b>{node.cluster_id} / {node.depth}</b></div></div><div className="mg-action-row"><button className="mg-primary" onClick={() => onClient(node.gid)}>Полная карточка</button><button onClick={() => onTransactions(node.gid)}>Операции</button></div></> : <Status message="Выберите клиента"/>}</Panel></div>
  </div></>;
}

export interface ClientsPageProps { filterProps: ClientFiltersProps; list?: Wrapped<Node>; loading: boolean; error: boolean; selected?: string; offset: number; onPage: (offset: number) => void; onClient: (gid: string) => void; onGraph: (gid: string) => void }
export function ClientsPage({ filterProps, list, loading, error, selected, offset, onPage, onClient, onGraph }: Readonly<ClientsPageProps>) {
  return <><Panel title="Поиск и фильтры"><ClientFilters {...filterProps}/><p className="mg-help">Фильтрация меняет только список; рассчитанные оценки и окружение клиента не пересчитываются.</p></Panel><Panel title={`Клиенты — ${list?.total?.toLocaleString("ru-RU") ?? "—"} записей`}><ClientTable items={list?.items} total={list?.total ?? 0} offset={offset} loading={loading} error={error} selected={selected} onSelect={onClient} onGraph={onGraph} onPage={onPage}/></Panel></>;
}

export interface ClientPageProps { node?: Node; loading: boolean; error: boolean; selected?: string; onClient: (gid: string) => void; onGraph: (gid: string) => void; onTransactions: (gid: string) => void; onMotifs: (gid: string) => void; onMotif: (id: string) => void }
export function ClientPage({ node, loading, error, selected, onClient, onGraph, onTransactions, onMotifs, onMotif }: Readonly<ClientPageProps>) {
  if (error) return <Status tone="error" message={`Клиент ${selected ?? ""} не найден или API недоступен.`}/>;
  if (loading || !node) return <Status message="Загружаем карточку клиента…"/>;
  return <><ClientHeader node={node} onGraph={() => onGraph(node.gid)} onTransactions={() => onTransactions(node.gid)} onMotifs={() => onMotifs(node.gid)}/><div className="mg-metric-grid"><MetricCard label="Вход" value={<MoneyValue value={node.in_kzt}/>} note={`${node.in_tx} операций`}/><MetricCard label="Выход" value={<MoneyValue value={node.out_kzt}/>} note={`${node.out_tx} операций`}/><MetricCard label="Оборот" value={<MoneyValue value={node.in_kzt + node.out_kzt}/>} note="Вход + выход"/><MetricCard label="Транзитное отношение" value={metric(node.pass_through)} note="Выход / вход"/></div><div className="mg-two-cols"><PriorityBreakdown contributions={node.details?.priority_contributions} total={node.priority_score}/><Panel title="Графовые и временные признаки"><div className="mg-keyvalues"><div><span>PageRank</span><b>{metric(node.pagerank)}</b></div><div><span>Betweenness</span><b>{metric(node.betweenness)}</b></div><div><span>Достижимые seed</span><b>{node.seed_reach}</b></div><div><span>Независимые ветви</span><b>{node.details?.independent_seed_branches?.count ?? "не рассчитано"}</b></div><div><span>Контрагенты вход / выход</span><b>{node.in_deg} / {node.out_deg}</b></div><div><span>HITS</span><b>{Object.entries(node.details?.hits ?? {}).filter(([, value]) => value != null).map(([key, value]) => `${key}: ${typeof value === "number" ? metric(value) : String(value)}`).join(" · ") || "не рассчитано"}</b></div></div></Panel></div><RuleTable rules={node.details?.rules}/><Panel title="Пути, мотивы и ограничения"><h3>Пути от seed</h3>{node.details?.seed_paths?.length ? node.details.seed_paths.map((path, index) => <p className="mg-path" key={index}>{path.map((gid, step) => <span key={gid + step}><GidButton gid={gid} onClick={onClient}/>{step < path.length - 1 && " → "}</span>)}</p>) : <p className="mg-muted">Пути не найдены</p>}<p>Независимые ветви: {node.details?.independent_seed_branches?.count ?? "не рассчитано"}</p><h3>Мотивы</h3><div className="mg-action-row">{node.details?.motif_ids?.slice(0, 8).map(id => <button key={id} onClick={() => onMotif(id)}>{id}</button>)}<button onClick={() => onMotifs(node.gid)}>Все мотивы клиента</button></div><h3>Ограничения</h3><ul className="mg-limitations">{node.details?.limitations?.map(item => <li key={item}>{item}</li>)}</ul></Panel></>;
}

type TransactionResponse = Wrapped<Transaction> & { daily: { date: string; direction: string; sum_kzt: number }[] };
export interface TransactionsPageProps { node?: Node; data?: TransactionResponse; loading: boolean; error: boolean; summary?: Summary; onGraph: (gid: string) => void; onClient: (gid: string) => void; onMotifs: (gid: string) => void }
export function TransactionsPage({ node, data, loading, error, summary, onGraph, onClient, onMotifs }: Readonly<TransactionsPageProps>) {
  if (!node) return <Status message="Загружаем клиента…"/>;
  const daily = Object.values((data?.daily ?? []).reduce<Record<string, { date: string; in: number; out: number }>>((acc, row) => {
    const item = acc[row.date] ?? { date: row.date, in: 0, out: 0 };
    item[row.direction === "in" ? "in" : "out"] += row.sum_kzt; acc[row.date] = item; return acc;
  }, {})).sort((a, b) => a.date.localeCompare(b.date));
  const incompleteReceipt = (item: Transaction) => {
    if (item.direction !== "in" || !summary) return false;
    const daysLeft = (Date.parse(summary.effective_config.period.end) - Date.parse(item.date)) / 86_400_000;
    return daysLeft >= 0 && daysLeft < summary.effective_config.typologies.temporal_max_days;
  };
  return <><ClientHeader node={node} onGraph={() => onGraph(node.gid)} onTransactions={() => {}} onMotifs={() => onMotifs(node.gid)}/><div className="mg-metric-grid"><MetricCard label="Вход" value={<MoneyValue value={node.in_kzt}/>} note={`${node.in_tx} операций`}/><MetricCard label="Выход" value={<MoneyValue value={node.out_kzt}/>} note={`${node.out_tx} операций`}/><MetricCard label="Всего операций" value={(data?.items.length ?? 0).toLocaleString("ru-RU")} note="Раздельный вход и выход"/></div><Panel title="Дневная динамика"><div className="mg-chart"><ResponsiveContainer width="100%" height={260}><BarChart data={daily}><CartesianGrid stroke="var(--line)"/><XAxis dataKey="date" tick={{ fill: "var(--muted)", fontSize: 11 }}/><YAxis tick={{ fill: "var(--muted)", fontSize: 11 }}/><Tooltip formatter={value => `${money.format(Number(value))} KZT`}/><Legend/><Bar dataKey="in" name="Поступления" fill="var(--accent)"/><Bar dataKey="out" name="Отправления" fill="var(--cyan)"/></BarChart></ResponsiveContainer></div><p className="mg-help">Даты известны до дня; однодневный порядок операций не определён.</p></Panel><Panel title="Таблица операций">{loading ? <Status message="Загружаем операции…"/> : error ? <Status tone="error" message="Не удалось загрузить операции."/> : <div className="mg-table-scroll"><table><thead><tr><th>Внутренний ID</th><th>Дата</th><th>Направление</th><th>Контрагент gid</th><th className="mg-num">Сумма</th></tr></thead><tbody>{data?.items.map(item => <tr key={item.transaction_id}><td className="mg-mono">{item.transaction_id}</td><td>{item.date}{incompleteReceipt(item) && <small className="mg-window-mark">Неполное окно</small>}</td><td>{item.direction === "in" ? "← Вход" : "Выход →"}</td><td><GidButton gid={item.counterparty_gid} onClick={onClient}/></td><td className="mg-num"><MoneyValue value={item.sum_kzt}/></td></tr>)}</tbody></table></div>}</Panel><Panel title="Временные сопоставления"><details className="matches"><summary>FIFO-совместимость 1–2 дня: {node.details?.temporal_matches?.length ?? 0} сопоставлений</summary><div className="mg-table-scroll"><table><thead><tr><th>Поступление</th><th>Отправление</th><th>Маршрут</th><th>Совместимый объём</th></tr></thead><tbody>{node.details?.temporal_matches?.slice(0, 100).map((match, index) => <tr key={index}><td>{String(match.incoming_date)}</td><td>{String(match.outgoing_date)}</td><td className="mg-mono">{String(match.source)} → {node.gid} → {String(match.target)}</td><td><MoneyValue value={Number(match.matched_tiyn) / 100}/></td></tr>)}</tbody></table></div></details><p className="mg-help">Временная совместимость не доказывает происхождение конкретных денег.</p></Panel></>;
}
