import { useState } from "react";
import { metric, type Disruption, type Sensitivity } from "../api";
import { contributionLabels } from "../data/ui";
import { GidButton, MetricCard, Panel, Status } from "../components/UI";

export interface DisruptionPageProps { items?: Disruption[]; loading: boolean; onClient: (gid: string) => void }
export function DisruptionPage({ items, loading, onClient }: Readonly<DisruptionPageProps>) {
  const [index, setIndex] = useState(0);
  const selected = items?.[index];
  return <><Panel title="Готовые сценарии удаления узлов"><select aria-label="Сценарий устойчивости" value={index} onChange={event => setIndex(Number(event.target.value))}>{items?.map((item, position) => <option value={position} key={position}>{item.kind} · {item.removed_gids.length} узлов</option>)}</select><p className="mg-help">Выбор готового сценария не запускает новый расчёт.</p></Panel>{loading && <Status message="Загружаем эксперименты…"/>}{selected && <><div className="mg-metric-grid"><MetricCard label="Крупнейшая компонента" value={`${selected.before.largest_component} → ${selected.after.largest_component}`}/><MetricCard label="Компоненты" value={`${selected.before.components} → ${selected.after.components}`}/><MetricCard label="Покрытие seed" value={`${metric(selected.before.seed_coverage)} → ${metric(selected.after.seed_coverage)}`}/><MetricCard label="Направленные пары seed" value={`${selected.before.directed_seed_pairs} → ${selected.after.directed_seed_pairs}`}/></div><Panel title="Исключаемые узлы"><div className="mg-action-row">{selected.removed_gids.map(gid => <GidButton key={gid} gid={gid} onClick={onClient}/>)}</div></Panel></>}<Panel title="Сравнение сценариев"><div className="mg-table-scroll"><table><thead><tr><th>Сценарий</th><th>Узлов</th><th>Крупнейшая компонента</th><th>Компоненты</th><th>Покрытие seed</th><th>Направленные пары seed</th></tr></thead><tbody>{items?.map((item, position) => <tr key={position} className={index === position ? "selected" : ""}><td><button className="mg-link" onClick={() => setIndex(position)}>{item.kind}</button></td><td>{item.removed_gids.length}</td><td>{item.before.largest_component} → {item.after.largest_component}</td><td>{item.before.components} → {item.after.components}</td><td>{metric(item.before.seed_coverage)} → {metric(item.after.seed_coverage)}</td><td>{item.before.directed_seed_pairs} → {item.after.directed_seed_pairs}</td></tr>)}</tbody></table></div></Panel><Status tone="warning" message="Модель удаляет узлы из наблюдаемого графа. Это структурный эксперимент, а не прогноз результата банковской блокировки."/></>;
}

export interface SensitivityPageProps { items?: Sensitivity[]; loading: boolean; onClient: (gid: string) => void }
export function SensitivityPage({ items, loading, onClient }: Readonly<SensitivityPageProps>) {
  const [index, setIndex] = useState(0);
  const selected = items?.[index];
  return <><Panel title="Десять готовых сценариев изменения весов">{loading && <Status message="Загружаем сценарии…"/>}<div className="mg-table-scroll"><table><thead><tr><th>Группа</th><th>Коэффициент</th><th>Пересечение топ-20</th><th>Макс. сдвиг</th><th>Вошли gid</th><th>Вышли gid</th></tr></thead><tbody>{items?.map((item, position) => <tr key={position} className={index === position ? "selected" : ""}><td><button className="mg-link" onClick={() => setIndex(position)}>{contributionLabels[item.group] ?? item.group}</button></td><td>×{item.factor}</td><td>{item.overlap_top20}/20</td><td>{item.max_position_change}</td><td className="mg-mono">{item.entered_gids.join(", ") || "—"}</td><td className="mg-mono">{item.left_gids.join(", ") || "—"}</td></tr>)}</tbody></table></div></Panel>{selected && <Panel title="Выбранный сценарий"><div className="mg-metric-grid"><MetricCard label="Группа" value={contributionLabels[selected.group] ?? selected.group}/><MetricCard label="Коэффициент" value={`×${selected.factor}`}/><MetricCard label="Пересечение топ-20" value={`${selected.overlap_top20}/20`}/><MetricCard label="Максимальный сдвиг" value={selected.max_position_change}/></div><p>Вошли: {selected.entered_gids.map(gid => <GidButton key={gid} gid={gid} onClick={onClient}/>)}</p><p>Вышли: {selected.left_gids.map(gid => <GidButton key={gid} gid={gid} onClick={onClient}/>)}</p></Panel>}<Status tone="warning" message="Изменяются только веса пяти готовых групп на ±20% с перенормировкой. Роли и центральности остаются прежними."/></>;
}
